# Generated by Django 4.1.2 on 2022-12-04 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_shippingadress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingadress',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.order'),
        ),
    ]
