# Generated by Django 4.1.2 on 2022-12-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_shippingadress_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
